baseURL = "https://docs.telemetryjet.com/"
languageCode = "en-us"
title = "TelemetryJet Documentation"
theme = "tjet-docs-theme"
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"
    filesUrl = "http://localhost:1313"
    cloudUrl = "http://localhost:8080"

[menu]
    [[menu.home]]
        identifier = "home_sections"
        title = "Sections"
        pre = "<span class='bp3-icon bp3-icon-bookmark'></span>"
        weight = 1
    [[menu.home]]
        identifier = "home_cli"
        parent = "home_sections"
        title = "TelemetryJet CLI"
        url = "/cli/"
        pre = "<span class='bp3-icon bp3-icon-cloud'></span>"
        weight = 2
    [[menu.home]]
        identifier = "home_arduino_sdk"
        parent = "home_sections"
        title = "TelemetryJet Arduino SDK"
        pre = "<span class='bp3-icon bp3-icon-cloud'></span>"
        url = "/arduino_sdk/"
        weight = 3
    [[menu.home]]
        identifier = "home_server"
        parent = "home_sections"
        title = "TelemetryJet Server"
        pre = "<span class='bp3-icon bp3-icon-cloud'></span>"
        url = "/server/"
        weight = 1
    [[menu.server]]
        identifier = "server_guides"
        title = "Guides"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.server]]
        identifier = "server_api"
        title = "API Reference"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.cli]]
        identifier = "cli_guides"
        title = "Guides"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.cli]]
        identifier = "cli_api"
        title = "API Reference"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.arduino_sdk]]
        identifier = "arduino_sdk_guides"
        title = "Guides"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.arduino_sdk]]
        identifier = "arduino_sdk_api"
        title = "API Reference"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2