baseURL = "https://docs.telemetryjet.com/"
languageCode = "en-us"
title = "TelemetryJet Documentation"
theme = "tjet-docs-theme"
sectionPagesMenu = "main"
pluralizelisttitles = false

[params]
    version = "v0.1.0"